---
title: "Norm score report"
params:
  groupname: NA
  taskname: NA
  tasknameCounterpart: NA
  path: NA
  storedModel: NA
  storedModelCounterpart: NA
  storedData: NA
  storedDataCounterpart: NA
  discrepantie: NA
  ageDays: NA
  meanproportion: NA
  meanproportionCounterpart: NA
  participantData: NA
  taskData: NA
  taskDataCounterpart: NA
  analizeData: NA
  analizeDataCounterpart: NA
---

```{r echo  = FALSE}
library(knitr)
h3(params$groupname)
kable(params$participantData)

```

```{r echo  = FALSE}
h3('Discrepantie analyse')
kable(params$discrepantie)

h3(params$taskname)
kable(params$taskData)
kable(params$analizeData)

```

```{r echo = FALSE}
source(paste(params$path, "plots.R", sep = '/'))
```

```{r echo = FALSE, results='hide'}
growthPlot(params$storedModel, params$storedData, params$ageDays, params$meanproportion)
```

```{r echo = FALSE}
h3(params$tasknameCounterpart)
kable(params$taskDataCounterpart)
kable(params$analizeDataCounterpart)
```

```{r echo = FALSE}
source(paste(params$path, "plots.R", sep = '/'))
```

```{r echo = FALSE, results='hide'}
growthPlot(params$storedModelCounterpart, params$storedDataCounterpart, params$ageDays, params$meanproportionCounterpart)
```
